### ISSUE TITLE
GraphQL backend setup

### ISSUE THREAD

**Issue by RZajacc** [helene-abiassi/CodaSk#35]
I'm gonna try to prepare a basic setup, and maybe at least one schema, query and resolver working so we can access something on the frontend

**Comment by helene-abiassi** [comment]
Small note for when we push my and your issue- I had to fix the Module{required:true} and anwerRoute import in index.js on my branch as well because I needed to get the server runni g
(to keep in mind when we merge as it might create conflict)

**Comment by RZajacc** [comment]
No problem, small conflicts especially when we expect them are fine. We can also merge stuff Monday morning, I'll just push once when I'm done
